config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
      end
    end
  end
  resources :notifications
  
  get "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_get
  post "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_post
  patch "notifications/:id/accept", to: "notifications#accepted", as: :notifications_accept
  patch "notifications/:id/reject", to: "notifications#rejected", as: :notifications_reject
  root "todo_lists#index"

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  validates :content, presence: true
  validates :priority, presence: true
  validates :deadline, presence: true
  
def completed?
   !completed_at.blank?
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
 before_action :set_todo_list
 before_action :set_todo_item, except: [:create]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/1/edit
def edit
  @todo_item = TodoItem.find(params[:id])
end

def create
 @todo_item = @todo_list.todo_items.create(todo_item_params)
 redirect_to @todo_list, notice: 'Task created.'
end

def destroy
 @todo_item = @todo_list.todo_items.find(params[:id])
 if @todo_item.destroy
  flash[:notice] = "Task deleted."
 else
  flash[:notice] = "Task could not be deleted."
 end
 redirect_to @todo_list 
end

def update
  respond_to do |format|
    if @todo_item.update(todo_item_params)
      format.html { redirect_to @todo_list, notice: 'Task updated.' }
      format.json { render :show, status: :ok, location: @todo_list }
    else
      format.html { render :edit }
      format.json { render json: @todo_list.errors, status: :unprocessable_entity }
    end
  end
end

def complete
 @todo_item.update_attribute(:completed_at, Time.now)
 redirect_to @todo_list, notice: "Task completed."
end

def uncomplete
  @todo_item.update_attribute(:completed_at, "")
  redirect_to @todo_list, notice: "Task uncompleted."
 end

private

def set_todo_list
 @todo_list = TodoList.find(params[:todo_list_id])
end

def set_todo_item
 @todo_item = @todo_list.todo_items.find(params[:id])
end

def todo_item_params
 params[:todo_item].permit(:content, :priority, :deadline)
end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
    <div class="field">
        <%= f.text_field :content, placeholder: "New task...", :required => 'required' %>
    </div>
    <div class="field">
        <%= f.label :priority %>
        <%= f.select :priority, options_for_select([["High"], ["Medium"],["Low"]]), :required => 'required' %>
    </div>
    <div class="field">
        <%= f.label :deadline %>
        <%= f.date_field :deadline, :value => Date.today, data:{provide:'datepicker'}, :required => 'required' %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
    <% if todo_item.completed? %>

    <div class="uncomplete">
        <%= link_to uncomplete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i class="fa fa-check"></i>
        <% end %>
    </div>
    <div class="todo_item">
        <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash fa-2x"></i>
        <% end %>
        <br></br>
        <%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id) do%>
        <i class="fa fa-edit fa-2x"></i>
        <% end %>
    </div>

    <% else %>
    <div class="complete">
        <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i class="fa fa-circle-thin"></i>
        <% end %>
    </div>

    <div class="todo_item">
        <p><%= todo_item.content %></p>
        <p>Priority: <%= todo_item.priority %></p>
        <p>Deadline date: <%= todo_item.deadline.strftime("%d-%m-%Y") %></p>
    </div>

    <div class="trash">
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash fa-2x"></i>
        <% end %>
        <br></br>
        <%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.id) do%>
        <i class="fa fa-edit fa-2x"></i>
        <% end %>
    </div>
    <% end %>
</div>

app/views/todo_items/edit.html.erb
<h1 class="todo_list_title">Editing Task</h1>
<br></br>
<div class="forms">
    <%= form_for(@todo_item, url: todo_list_todo_item_path) do |f| %>
    <div class="field">
        <%= f.text_field :content, placeholder: "New task...", :required => 'required' %>
    </div>
    <div class="field">
        <%= f.label :priority %>
        <%= f.select :priority, options_for_select([["High"], ["Medium"],["Low"]]), :required => 'required' %>
    </div>
    <div class="field">
        <%= f.label :deadline %>
        <%= f.date_field :deadline, :value => Date.today, data:{provide:'datepicker'}, :required => 'required' %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
    <% end %>
</div>
<div class="links">
    <%= link_to @todo_list do%>
    <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
</div>