config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
      end
    end
  end
  resources :notifications
  
  get "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_get
  post "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_post
  patch "notifications/:id/accept", to: "notifications#accepted", as: :notifications_accept
  patch "notifications/:id/reject", to: "notifications#rejected", as: :notifications_reject
  root "todo_lists#index"

end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    belongs_to :user
    has_many :todo_items, 
    dependent: :delete_all
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  
  # GET /todo_lists
  def index
    if user_signed_in?
      @shared = Sharedlist.where(:id_user => current_user.id)
      #puts(@shared.id_user)
      @todo_lists = TodoList.where(:user_id => current_user.id)
      for s in @shared
        @todo_lists = @todo_lists + TodoList.where(:id => s.id_list)
      end
    end
    #@todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  def show
  end

  # GET/todo_lists/1/share
  def share
    if !params[:commit].nil?
      receiver = User.find_by_username(params[:receiver])
      Notification.create(status: "Pending", sender_id: current_user.id, receiver_id: receiver.id, todo_list: params[:id])
    end
  end

  # GET /todo_lists/new
  def new
    #@todo_list = TodoList.new
    @todo_list = current_user.todo_lists.build
  end

  # POST /todo_lists
  def create
    #@todo_list = TodoList.new(todo_list_params)
    @todo_list = current_user.todo_lists.build(todo_list_params)
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'To-Do list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # PATCH/PUT /todo_lists/1
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'To-Do list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  def destroy
    if @todo_list.user_id == current_user.id
      @todo_list.destroy
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'To-Do list was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Could not delete To-Do list as you are not the owner.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    #def pending
    #  if user_signed_in?
    #    @notifications = Notification.where(:receiver_id => current_user.id, :status => "Pending")
    #    if !@notifications.nil?
    #      render html: "<script>alert('You've new notifications!')</script>".html_safe
    #    end
    #  end
    #end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
<% if todo_list.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

    <ul>
        <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title,:required => 'required' %>
</div>

<div class="field">
    <%= form.label :description %>
    <%= form.text_area :description,:required => 'required' %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing To-Do List</h1>
<div class="forms">
    <%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
    <%= link_to @todo_list do%>
        <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
</div>

app/views/todo_lists/index.html.erb
<% if user_signed_in? %>
    <%-# <p id="notice"><%= notice </p> - %>
    
    <% @todo_lists.each do |todo_list| %>
    <div class="index_row clearfix">
        <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
        <p class="todo_list_sub_title"><%= todo_list.description %></p>
        <br></br>
        <p class= "todo_list_sub_title">Created by: <%= todo_list.user.username %></p>
        <div class="trash">
            <%= link_to todo_list, method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash fa-2x"></i>
            <% end %>
        </div>
    </div>
    <% end %>

    <div class="links">
        <%= link_to '<button type="button" class="btn btn-primary btn-sm">Create new list</button>'.html_safe, new_todo_list_path, class: "link-color" %>
    </div>
<% else %>
    <%= render 'layouts/static_main_page' %>
<% end %>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New To-Do List</h1>
<div class="forms">
    <%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
    <%= link_to todo_lists_path do%>
        <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
</div>

app/views/todo_lists/share.html.erb
<h1 class="todo_list_title">Sharing To-Do List</h1>
<br></br>
<%= form_with(model: @todo_list, local: true) do |form| %>
    <div class="forms">
        <%= form.label :receiver %>
        <%= form.select(:receiver, options_for_select((User.where.not username: current_user.username).collect(&:username)), :required => 'required', :style => "width:250px" ) %>
        <br></br>
        <div class="actions">
        <%= form.submit %>
        </div>
    </div>

    
<% end %>
<div class="links">
    <%= link_to todo_list_path do%>
        <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
</div>

app/views/todo_lists/show.html.erb
<%-# <p id="notice"><%= notice </p> - %>
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>
<div class="index_row clearfix">
    <div id="todo_items_wrapper">
        <%= render @todo_list.todo_items %>
        <div id="form">
            <%= render "todo_items/form" %>
        </div>
    </div>
</div>
<div class="links">
    <%= link_to todo_lists_path do%>
    <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
    | <%= link_to edit_todo_list_path(@todo_list) do%>
    <i class="fa fa-edit fa-2x"></i>
    <% end %>
    | <%= link_to share_todo_list_get_path(@todo_list) do%>
    <i class="fa fa-share fa-2x"></i>
    <% end %>
    | <%= link_to todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } do%>
    <i class="fa fa-trash fa-2x"></i>
    <% end %>
</div>