config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
      end
    end
  end
  resources :notifications
  
  get "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_get
  post "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_post
  patch "notifications/:id/accept", to: "notifications#accepted", as: :notifications_accept
  patch "notifications/:id/reject", to: "notifications#rejected", as: :notifications_reject
  root "todo_lists#index"

end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

    def index
        if user_signed_in?
            @notifications = Notification.where(:receiver_id => current_user.id, :status => "Pending")
        end
        #@notifications = Notification.all
    end

    def show
    end

    def new
        @notification = Notification.new
        #@notification = current_user.notifications.build
    end

    def create
        @notification = notifications.build(notification_params)
        if @todo_list.save
            format.html { redirect_to todo_list_path, notice: 'Notification was successfully created.' }
        end
    end

    def destroy
        @notification.destroy
        redirect_to root_url, notice: 'Notification was successfully destroyed.'
    end

    def accepted
        @notification = Notification.find(params[:id])
        @notification.update_attribute(:status, "Attended")
        Sharedlist.create(id_list: @notification.todo_list, id_user: @notification.receiver_id)
        redirect_to notifications_path, notice: "List accepted."
    end

    def rejected
        @notification = Notification.find(params[:id])
        @notification.update_attribute(:status, "Attended")
        redirect_to notifications_path, notice: "List rejected."
    end

    private

    def notification_params
        params[:notification].permit(:status, :sender_id, :receiver_id, :todo_list)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<h2 class="todo_list_title">Notifications</h2>


<div class="index_row clearfix">
    <% @notifications.each do |notification| %>
    <div id="notification_wrapper">
        <div class="row clearfix">
            <div class="notification_item">
                <div class="notification">
                    <!--- ENLACE A VISTA PREVIA <div class="notification_title"><%= link_to (TodoList.find(notification.todo_list)).title, notification %> </div> !-->
                    <div class="notification_title"><%= (TodoList.find(notification.todo_list)).title%> </div> 
                    <p>Description: <%= TodoList.find(notification.todo_list).description %></p> 
                    <p>Owner: <%= (User.find(notification.sender_id)).username %></p>   
                    <br></br>
                </div>
            </div>
            <div class="notification_options">
                <br></br>
                <%= link_to notifications_accept_path(notification), method: :patch do %>
                    <i class="fa fa-check fa-2x"></i>
                <% end %>
                        <br></br>
                <%= link_to notifications_reject_path(notification), method: :patch do%>
                    <i class="fa fa-times fa-2x"></i>
                <% end %>
            </div>  
        </div>
    </div>
<% end %>
</div>

<div class="links">
    <%= link_to todo_lists_path do%>
        <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>
</div>