config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
      end
    end
  end
  resources :notifications
  
  get "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_get
  post "todo_lists/:id/share", to: "todo_lists#share", as: :share_todo_list_post
  patch "notifications/:id/accept", to: "notifications#accepted", as: :notifications_accept
  patch "notifications/:id/reject", to: "notifications#rejected", as: :notifications_reject
  root "todo_lists#index"

end

app/views/layouts/_navigationbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "TEAM_01", root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav">
        
    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>

        <form class="navbar-form navbar-left form-inline my-2 my-lg-0">
            <% if current_user.present? %>
                | <li><%= link_to '<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Notifications</button>'.html_safe, notifications_path, class: "link-color" %></li>
                | <li><%= link_to '<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Account</button>'.html_safe, edit_user_registration_path, class: "link-color" %></li>
                | <li><%= link_to '<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Log Out</button>'.html_safe, destroy_user_session_path, method: :delete, class: "link-color" %></li>
            <% else %>
                | <li><%= link_to '<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Sign Up</button>'.html_safe, new_user_registration_path, class: "link-color" %></li>
                | <li><%= link_to '<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Log In</button>'.html_safe, new_user_session_path, class: "link-color" %></li>
            <% end %>
        </form>
    </div>
</nav>

app/views/layouts/_static_main_page.html.erb
<div class="main_page">
    <h2>To-Do List application</h2>
    <p>"Never leave till tomorrow that which you can do today." - Benjamin Franklin</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <%= render "layouts/navigationbar" %>
    <div class="container">
        <% flash.each do |type, msg| %>
            <div class="alert alert-info">
                <%= msg %>
            </div>
        <% end %>
        <%= yield %>
    </div>
</body>

</html>